# Supported funding model platforms

github: [swapptech]                  # GitHub Sponsors
open_collective: swapp-technologies   # Open Collective
buy_me_a_coffee: swappTechOpenSource           # Buy Me a Coffee
custom: ['https://www.swapp.solutions']
